# Generated by Django 4.2.15 on 2024-08-18 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenuCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок будет использоваться в качестве текста кнопки', max_length=200, verbose_name='Заголовок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('description', models.TextField(blank=True, help_text='Описание будет использоваться в тексте команды', max_length=500, verbose_name='Описание')),
                ('role', models.CharField(choices=[('parent', 'родитель'), ('logoped', 'логопед')], max_length=100, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Настраиваемый пункт меню',
                'verbose_name_plural': 'Настраиваемые пункты меню',
            },
        ),
        migrations.CreateModel(
            name='URLLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок будет использоваться в качестве текста кнопки', max_length=200, verbose_name='Заголовок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='commands.mainmenucommand')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок будет использоваться в качестве текста кнопки', max_length=200, verbose_name='Заголовок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('file', models.FileField(upload_to='attachments', verbose_name='Файл')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='commands.mainmenucommand')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
