# Generated by Django 4.2.15 on 2024-08-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenucommand',
            name='description',
            field=models.TextField(blank=True, help_text='Описание будет использоваться в тексте команды', max_length=4096, verbose_name='Описание'),
        ),
    ]
