name: privet_logoped_chat_bots
volumes:
  db_data:
  media:
  static:

services:
  privet_logoped_db:
    image: postgres:16
    env_file: .env
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ../django_app/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - media:/app/media/
      - static:/app/static/
    depends_on:
      - privet_logoped_db
  nginx:
    image: nginx:1.27
    env_file: .env
    restart: always
    ports: 
      - "${OUT_PORT}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - media:/media/
    depends_on:
      - backend
  telegram_bot:
    build:
      context: ../telegram_bot/
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - backend
    volumes:
      - media:/media/
  vk_bot:
    build:
      context: ../vk_bot/
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - backend
    volumes:
      - media:/media/