# Generated by Django 4.2.15 on 2024-08-18 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('parent', 'родитель'), ('logoped', 'логопед')], max_length=100)),
                ('question_text', models.TextField(max_length=4096)),
                ('message_id', models.PositiveBigIntegerField(unique=True, verbose_name='ID сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['telegramuser', 'vkuser']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Вопрос пользователя',
                'verbose_name_plural': 'Вопросы пользователей',
            },
        ),
        migrations.CreateModel(
            name='QueryAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
                ('user_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='user_queries.userquery')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
            },
        ),
        migrations.AddIndex(
            model_name='userquery',
            index=models.Index(fields=['content_type', 'object_id'], name='user_querie_content_86fe8d_idx'),
        ),
    ]
